from enum import IntEnum, StrEnum
from typing import Iterator, Literal, overload

class KeyType(StrEnum):
    KEYRING = "keyring"
    USER = "user"
    LOGON = "logon"
    BIG_KEY = "big_key"

class SpecialKeyring(IntEnum):
    THREAD = -1
    PROCESS = -2
    SESSION = -3
    USER = -4
    USER_SESSION = -5

class KeyringError(OSError): ...

class TNKey:
    @property
    def description(self) -> str | None: ...
    @property
    def key_type(self) -> str | None: ...
    @property
    def uid(self) -> int | None: ...
    @property
    def gid(self) -> int | None: ...
    @property
    def permissions(self) -> int | None: ...
    @property
    def serial(self) -> int: ...
    def read_data(self) -> bytes: ...
    def set_timeout(self, timeout: int) -> None: ...

class TNKeyring:
    @property
    def key(self) -> TNKey: ...
    def clear(self) -> None: ...
    def list_keyring_contents(
        self,
        *,
        unlink_expired: bool = False,
        unlink_revoked: bool = False,
    ) -> list[TNKey | TNKeyring]: ...
    def iter_keyring_contents(
        self,
        *,
        unlink_expired: bool = False,
        unlink_revoked: bool = False,
    ) -> TNKeyringIter: ...
    @overload
    def search(self, *, key_type: Literal[KeyType.KEYRING], description: str) -> TNKeyring: ...
    @overload
    def search(self, *, key_type: str, description: str) -> TNKey | TNKeyring: ...
    def unlink_key(self, serial: int, /) -> None: ...

class TNKeyringIter:
    def __iter__(self) -> Iterator[TNKey | TNKeyring]: ...
    def __next__(self) -> TNKey | TNKeyring: ...

@overload
def request_key(*, key_type: Literal[KeyType.KEYRING], description: str) -> TNKeyring: ...
@overload
def request_key(*, key_type: KeyType, description: str) -> TNKey | TNKeyring: ...
def get_persistent_keyring(*, uid: int = -1) -> TNKeyring: ...
def add_key(
    *, key_type: str, description: str, data: bytes, target_keyring: int
) -> TNKey: ...
def add_keyring(*, description: str, target_keyring: int) -> TNKeyring: ...
def revoke_key(*, serial: int) -> None: ...
def invalidate_key(*, serial: int) -> None: ...
